// <auto-generated />
namespace ManTestAppWebForms.ApplicationUserDataMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class secondwithrole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondwithrole));
        
        string IMigrationMetadata.Id
        {
            get { return "201703150940450_secondwithrole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
