<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ProjectIndex.aspx.cs" Inherits="ManTestAppWebForms.Views.ProjectIndex" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    $("[src*=plus]").live("click", function () {
        $(this).closest("tr").after("<tr><td></td><td colspan = \'999\'>" + $(this).next().html() + "</td></tr>")
        $(this).attr("src", "../images/minus.png");
    });
    $("[src*=minus]").live("click", function () {
        $(this).attr("src", "../images/plus.png");
        $(this).closest("tr").next().remove();
    });
</script>
    <h2>Projects</h2>
    <asp:HyperLink NavigateUrl="~/Views/ProjectCreate" Text="Add New Project" runat="server" />
    <asp:GridView runat="server" ID="gv_ProjectIndex"
        DataKeyNames="Id"
        SelectMethod="GetData_ProjectIndex"
        DeleteMethod="gv_ProjectIndex_DeleteItem"
        UpdateMethod="gv_ProjectIndex_UpdateItem"
        ItemType="ManTestAppWebForms.Models.Project"
        AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" AutoGenerateSelectButton="false"
        OnRowDeleted="gv_ProjectIndex_RowDeleted"
        CssClass="table table-hover table-striped"
        AllowSorting="true" AllowPaging="true" PageSize="5"
        AutoGenerateColumns="false"
        OnSelectedIndexChanged="gv_ProjectIndex_SelectedIndexChanged"
        OnRowDataBound="parent_OnRowDataBound">
        <Columns>
            <asp:TemplateField>
                <ItemTemplate>
                    <img alt="" src="../images/plus.png" style="cursor: pointer" />
                    <asp:Panel ID="pnlOrders" runat="server" Style="display: none">
                    <asp:GridView runat="server" 
                        AutoGenerateColumns="false"  ID="Module" EmptyDataText="No related Modules" Visible="true"
                         OnRowDataBound="child_OnRowDataBound">
                        <Columns>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <img alt="" src="../images/plus.png" style="cursor: pointer" />
                                        <asp:Panel ID="pnlTestCase" runat="server" Style="display: none">
                                        <asp:GridView runat="server" 
                                                      AutoGenerateColumns="false"  ID="TestCase" EmptyDataText="No related TestCases" Visible="true"
                                                      OnRowDataBound="grandchild_OnRowDataBound">
                                            <Columns>
                                                <asp:BoundField DataField="Id" HeaderText="ID"></asp:BoundField>
                                                <asp:BoundField DataField="Title" HeaderText="TITLE"></asp:BoundField>
                                                <asp:BoundField DataField="Description" HeaderText="DESCRIPTION"></asp:BoundField>
                                            </Columns>
                                        </asp:GridView>
                                        </asp:Panel>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            <asp:BoundField DataField="Id" HeaderText="ID"></asp:BoundField>
                            <asp:BoundField DataField="Title" HeaderText="TITLE"></asp:BoundField>
                            <asp:BoundField DataField="Description" HeaderText="DESCRIPTION"></asp:BoundField>
                        </Columns>
                    </asp:GridView>
                    </asp:Panel>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="Id" HeaderText="ID"></asp:BoundField>
            <asp:BoundField DataField="Title" HeaderText="TITLE"></asp:BoundField>
            <asp:BoundField DataField="Description" HeaderText="DESCRIPTION"></asp:BoundField>
            <asp:hyperlinkfield headertext="Add Module"
                            datanavigateurlfields="Id" 
                            datanavigateurlformatstring="ModuleCreate.aspx?projectId={0}"
                            Text="Add Module"
              />
            <asp:CommandField ShowEditButton="True" ShowDeleteButton="True"/>
        </Columns>
    </asp:GridView>
</asp:Content>
                           <%-- NavigateUrl="~/Views/ModuleCreate" --%>
