<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ProjectDetails.aspx.cs" Inherits="ManTestAppWebForms.Views.ProjectDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div>
    <asp:SiteMapPath ID="SiteMapPath1" runat="server"></asp:SiteMapPath>
    </div>
    <br/>
    <div style="width:100%;">
    <asp:Label ID="Label2" runat="server" Text="Related Modules"  CssClass="labelmantest"></asp:Label>
    <asp:GridView ID="GridViewModules" runat="server"
         ItemType="ManTestAppWebForms.Models.Module"
         DataKeyNames="Id"
         SelectMethod="GetModules"
         DeleteMethod="GridViewModules_DeleteItem"
         UpdateMethod="GridViewModules_UpdateItem"
         AutoGenerateColumns="false"
         AutoGenerateDeleteButton="false"
         AutoGenerateEditButton="false"
         CssClass="table tablegridview"
         OnRowCreated="GridViewModules_RowCreated"
         >
        <EmptyDataTemplate>
            No data found
        </EmptyDataTemplate>
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="true"></asp:BoundField>
            <asp:BoundField DataField="Title" HeaderText="TITLE"></asp:BoundField>
            <asp:BoundField DataField="Description" HeaderText="DESCRIPTION" ItemStyle-CssClass="col" ItemStyle-Width="100px"></asp:BoundField>
            <asp:hyperlinkfield 
                            datanavigateurlfields="Id" 
                            datanavigateurlformatstring="ModuleDetails.aspx?moduleId={0}"
                            Text="Details>"/>
            <asp:CommandField ShowEditButton="True"/>
            <asp:CommandField ShowDeleteButton="True"/>
        </Columns>
    </asp:GridView>

    <asp:Label ID="Label3" runat="server" Text="Related Test Cases"  CssClass="labelmantest"></asp:Label>

    <asp:GridView ID="GridViewTestCases" runat="server"
         ItemType="ManTestAppWebForms.Models.TestCase"
         DataKeyNames="Id"
         SelectMethod="GetTestCases"
         DeleteMethod="GridViewTestCases_DeleteItem"
         UpdateMethod="GridViewTestCases_UpdateItem"
         AutoGenerateColumns="false"
         AutoGenerateDeleteButton="false"
         AutoGenerateEditButton="false"
         CssClass="table tablegridview"
         OnRowCreated="GridViewTestCases_RowCreated"
         >
        <EmptyDataTemplate>
            No data found
        </EmptyDataTemplate>
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="true"></asp:BoundField>
            <asp:BoundField DataField="Title" HeaderText="TITLE"></asp:BoundField>
            <asp:BoundField DataField="Description" HeaderText="DESCRIPTION" ItemStyle-CssClass="col"></asp:BoundField>
            <asp:hyperlinkfield 
                            datanavigateurlfields="Id" 
                            datanavigateurlformatstring="TestCaseDetails.aspx?testCaseId={0}"
                            Text="Details>"/>
            <asp:CommandField ShowEditButton="True"/>
            <asp:CommandField ShowDeleteButton="True"/>
        </Columns>
    </asp:GridView>
    </div>
</asp:Content>
