<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ProjectDetails.aspx.cs" Inherits="ManTestAppWebForms.Views.ProjectDetails" %>
<asp:Content ID="ContentTreeView" ContentPlaceHolderID="MainContent" runat="server">
    <asp:TreeView ID="TreeViewModules" runat="server"  CssClass="TreeView"  
                  OnSelectedNodeChanged="TreeViewModules_SelectedNodeChanged" 
                  OnTreeNodeCheckChanged="TreeViewModules_TreeNodeCheckChanged"
                  SelectedNodeStyle-BackColor="#33cccc">

    </asp:TreeView>
    </asp:Content>
<%--<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Label ID="Label1" runat="server" Text='<%# "Project " + currentProject.Title %>'  CssClass="legend titlemantest"></asp:Label>
    <br/>
    <asp:Label ID="Label2" runat="server" Text="Related Modules"  CssClass="labelmantest"></asp:Label>
    <asp:GridView ID="GridViewModules" runat="server"
         ItemType="ManTestAppWebForms.Models.Module"
         DataKeyNames="Id"
         SelectMethod="GetModules"
         DeleteMethod="GridViewModules_DeleteItem"
         UpdateMethod="GridViewModules_UpdateItem"
         AutoGenerateColumns="false"
         AutoGenerateDeleteButton="false"
         AutoGenerateEditButton="false"
         CssClass="table tablegridview">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="true"></asp:BoundField>
            <asp:BoundField DataField="Title" HeaderText="TITLE"></asp:BoundField>
            <asp:BoundField DataField="Description" HeaderText="DESCRIPTION"></asp:BoundField>
            <asp:hyperlinkfield 
                            datanavigateurlfields="Id" 
                            datanavigateurlformatstring="ModuleDetails.aspx?moduleId={0}"
                            Text="Details"/>
            <asp:CommandField ShowEditButton="True"/>
            <asp:CommandField ShowDeleteButton="True"/>
        </Columns>
    </asp:GridView>

    <asp:Label ID="Label3" runat="server" Text="Related Test Cases"  CssClass="labelmantest"></asp:Label>

    <asp:GridView ID="GridViewTestCases" runat="server"
         ItemType="ManTestAppWebForms.Models.TestCase"
         DataKeyNames="Id"
         SelectMethod="GetTestCases"
         DeleteMethod="GridViewTestCases_DeleteItem"
         UpdateMethod="GridViewTestCases_UpdateItem"
         AutoGenerateColumns="false"
         AutoGenerateDeleteButton="false"
         AutoGenerateEditButton="false"
         CssClass="table tablegridview">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="true"></asp:BoundField>
            <asp:BoundField DataField="Title" HeaderText="TITLE"></asp:BoundField>
            <asp:BoundField DataField="Description" HeaderText="DESCRIPTION"></asp:BoundField>
            <asp:hyperlinkfield 
                            datanavigateurlfields="Id" 
                            datanavigateurlformatstring="TestCaseDetails.aspx?testCaseId={0}"
                            Text="Details"/>
            <asp:CommandField ShowEditButton="True"/>
            <asp:CommandField ShowDeleteButton="True"/>
        </Columns>
    </asp:GridView>
</asp:Content>--%>
