<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ProjectIndex.aspx.cs" Inherits="ManTestAppWebForms.Views.ProjectIndex" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <div>
    <asp:SiteMapPath ID="SiteMapPath1" runat="server"></asp:SiteMapPath>
    </div>
    <div>
    <asp:Label ID="lblProjects" runat="server" Text="Projects" CssClass="legend titlemantest"></asp:Label>
    </div>
    <br/>
    <div>
    <asp:HyperLink NavigateUrl="~/Views/ProjectCreate" Text="Add New Project" runat="server" />
    </div>
    <asp:GridView runat="server" ID="gv_ProjectIndex"
        DataKeyNames="Id"
        SelectMethod="GetData_ProjectIndex"
        DeleteMethod="gv_ProjectIndex_DeleteItem"
        UpdateMethod="gv_ProjectIndex_UpdateItem"
        ItemType="ManTestAppWebForms.Models.Project"
        AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" AutoGenerateSelectButton="false"
        OnRowDeleted="gv_ProjectIndex_RowDeleted"
        CssClass="table tablegridview"
        AllowSorting="true" AllowPaging="true" PageSize="5"
        AutoGenerateColumns="false"
        EditRowStyle-CssClass="SelectedRowStyle">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="true"  ControlStyle-BackColor="#ff0066"></asp:BoundField>
            <asp:BoundField DataField="Title" HeaderText="TITLE" ></asp:BoundField>
            <asp:BoundField DataField="Description" HeaderText="DESCRIPTION"></asp:BoundField>
            <asp:hyperlinkfield 
                            datanavigateurlfields="Id" 
                            datanavigateurlformatstring="ModuleCreate.aspx?projectId={0}"
                            Text="Add Module"/>
            <asp:hyperlinkfield 
                                DataNavigateUrlFields="Id"
                                DataNavigateUrlFormatString="AttachTestCase.aspx?projectId={0}"
                                Text="Add TestCase"/>
            <asp:TemplateField >
                <ItemTemplate>
                    <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl='<%# String.Format("ProjectDetails.aspx?projectId={0}", Item.Id) %>'> Details ></asp:HyperLink>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:CommandField ShowEditButton="True"/>
            <asp:CommandField ShowDeleteButton="True"/>
        </Columns>
    </asp:GridView>
</asp:Content>
