<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="StepDetails.aspx.cs" Inherits="ManTestAppWebForms.Views.StepDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Label ID="Label2" runat="server" Text='<%# Step.Title %>'  Font-Bold="true" Font-Size="Larger"></asp:Label>
    <div class="form-group">
    <asp:Label ID="lblProject" runat="server" Text="Related Project" class="col-lg-2 control-label"></asp:Label>
    <asp:TextBox ID="TextBoxProject" runat="server" Text='<%# Step.TestCase.Project.Description %>' class="form-control" ReadOnly="true"></asp:TextBox>
    </div>
   <%-- <div class="form-group">
    <asp:Label ID="lblModule" runat="server" Text="Module" class="col-lg-2 control-label"></asp:Label>
    <asp:TextBox ID="TextBoxModule" runat="server" Text='<%# Eval("Step.TestCase.Module.Title") == DBNull.Value ? "" : Eval("Step.TestCase.Module.Title") %>' class="form-control"></asp:TextBox>
    </div>--%>
    <div class="form-group">
    <asp:Label ID="lblTestCase" runat="server" Text="Related TestCase" class="col-lg-2 control-label"></asp:Label>
    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Step.TestCase.Title%>' class="form-control" ReadOnly="true"></asp:TextBox>
    </div>
    
    <div class="form-group">
        <br></br>
    <asp:Label ID="lblTitle" runat="server" Text="Title" class="col-lg-2 control-label"></asp:Label>
    <asp:TextBox ID="TextBoxTitle" runat="server" Text='<%# Step.Title %>' class="form-control"></asp:TextBox>
    </div>

    <div class="form-group">
    <asp:Label ID="lblDescription" runat="server" Text="Description" class="col-lg-2 control-label"></asp:Label>
    <asp:TextBox ID="TextBoxDescription" runat="server" Text='<%# Step.Description %>' class="form-control"></asp:TextBox>
    </div>
    <div class="form-group">
    <asp:Label ID="Label1" runat="server" Text="Attachments" class="col-lg-2 control-label"></asp:Label>
    <asp:GridView ID="gvAttachments" runat="server"
                  ItemType="ManTestAppWebForms.Models.Attachment"
                  DataKeyNames="Id"
                  AutoGenerateColumns="false"
                  AutoGenerateDeleteButton="false"
                  AutoGenerateEditButton="false"
                  SelectMethod="gvAttachments_GetData"
                  DeleteMethod="gvAttachments_DeleteItem"
                  UpdateMethod="gvAttachments_UpdateItem"
                  CssClass="table tablegridview">
        <Columns>
            <asp:BoundField DataField="Id" ReadOnly="true" HeaderText="ID">
                </asp:BoundField>
            <asp:BoundField DataField="FileName" HeaderText="FileName">
                </asp:BoundField>
            <%--<asp:BoundField DataField="Url" HeaderText="Url">
                </asp:BoundField>--%>
            <asp:hyperlinkfield 
                            datanavigateurlfields="Id" 
                            datanavigateurlformatstring="AttachmentOpen.aspx?attachmentId={0}"
                            Text="Open"
                             />
            <asp:CommandField ShowEditButton="True"/>
            <asp:CommandField ShowDeleteButton="True"/>
        </Columns>
    </asp:GridView>
    
    <asp:Button ID="btnAddAttachment" runat="server" Text="Add Attachment"   OnClick="btn_AddAttachment" class="btn btn-default" />
        </div>
</asp:Content>

