<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="StepDetails.aspx.cs" Inherits="ManTestAppWebForms.Views.StepDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="form-group">
    <asp:Label ID="lblTitle" runat="server" Text="Title" class="col-lg-2 control-label"></asp:Label>
    <asp:TextBox ID="TextBoxTitle" runat="server" Text='<%# Step.Title %>' class="form-control"></asp:TextBox>
    </div>

    <div class="form-group">
    <asp:Label ID="lblDescription" runat="server" Text="Description" class="col-lg-2 control-label"></asp:Label>
    <asp:TextBox ID="TextBoxDescription" runat="server" Text='<%# Step.Description %>' class="form-control"></asp:TextBox>
    </div>

<%-- 
    <div class="form-group">
      <label for="textArea" class="col-lg-2 control-label">Textarea</label>
      <div class="col-lg-10">
        <textarea class="form-control" rows="3" id="textArea"></textarea>
        <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
      </div>
     </div>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
      <div class="col-lg-10">
        <input class="form-control" id="inputEmail" placeholder="Email" type="text">
      </div>
    </div>--%>
    <div class="form-group">
    <asp:Label ID="Label1" runat="server" Text="Attachments" class="col-lg-2 control-label"></asp:Label>
    <%--<asp:ListView ID="ListViewAttachments" runat="server" SelectMethod="ListViewAttachments_GetData"
         ItemType="ManTestAppWebForms.Models.Attachment">
        <ItemTemplate>
            <li title='<%# Eval("Url") %>'></li>
            <asp:Label ID="Label2" runat="server" Text='<%# Eval("Url") %>'></asp:Label>
        </ItemTemplate>
    </asp:ListView>--%>
    <asp:GridView ID="gvAttachments" runat="server"
                  ItemType="ManTestAppWebForms.Models.Attachment"
                  DataKeyNames="Id"
                  AutoGenerateColumns="false"
                  AutoGenerateDeleteButton="false"
                  AutoGenerateEditButton="false"
                  SelectMethod="gvAttachments_GetData"
                  DeleteMethod="gvAttachments_DeleteItem"
                  UpdateMethod="gvAttachments_UpdateItem"
                  CssClass="table">
        <Columns>
            <asp:BoundField DataField="Id" ReadOnly="true" HeaderText="ID">
                </asp:BoundField>
            <asp:BoundField DataField="FileName" HeaderText="FileName">
                </asp:BoundField>
            <asp:BoundField DataField="Url" HeaderText="Url">
                </asp:BoundField>
            <asp:hyperlinkfield 
                            datanavigateurlfields="Id" 
                            datanavigateurlformatstring="AttachmentOpen.aspx?attachmentId={0}"
                            Text="Open"
                             />
            <asp:CommandField ShowEditButton="True"/>
            <asp:CommandField ShowDeleteButton="True"/>
        </Columns>
    </asp:GridView>
    
    <asp:Button ID="btnAddAttachment" runat="server" Text="Add Attachment"   OnClick="btn_AddAttachment" class="btn btn-default" />
        </div>
    
    </asp:Content>
