<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="TestCaseDetails.aspx.cs" Inherits="ManTestAppWebForms.Views.TestCaseDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div>
    <asp:SiteMapPath ID="SiteMapPath1" runat="server"></asp:SiteMapPath>
    </div>
    <asp:Label ID="LabelTestCase" runat="server" ></asp:Label>
    <%--<asp:TreeView ID="TreeViewTestCase" runat="server" OnSelectedNodeChanged="TreeViewTestCase_SelectedNodeChanged" ></asp:TreeView>--%>
    <asp:GridView ID="GridViewSteps" runat="server"
                     ItemType="ManTestAppWebForms.Models.Step"
                     DataKeyNames="Id"
                     DeleteMethod="GridViewSteps_DeleteItem"
                     UpdateMethod="GridViewSteps_UpdateItem"
                     SelectMethod="GridViewSteps_GetData"
                     AutoGenerateColumns="false"
                     AutoGenerateDeleteButton="false"
                     AutoGenerateEditButton="false"
                     CssClass="table tablegridview">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="true"></asp:BoundField>
            <asp:BoundField DataField="Title" HeaderText="TITLE"></asp:BoundField>
            <asp:BoundField DataField="Description" HeaderText="DESCRIPTION"></asp:BoundField>
            <asp:hyperlinkfield 
                            datanavigateurlfields="Id" 
                            datanavigateurlformatstring="StepDetails.aspx?stepId={0}"
                            Text="Details >"/>
            <asp:CommandField ShowEditButton="True"/>
            <asp:CommandField ShowDeleteButton="True"/>
        </Columns>

    </asp:GridView>
</asp:Content>

