<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="TestCaseDetails.aspx.cs" Inherits="ManTestAppWebForms.Views.TestCaseDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div>
    <asp:SiteMapPath ID="SiteMapPath1" runat="server"></asp:SiteMapPath>
    </div>
     <div>
    <asp:Label ID="LabelProjectTitle" runat="server"  CssClass="legend titlemantest"></asp:Label>
    </div>
    <div>
    <asp:Label ID="LabelModuleTitle" runat="server"  CssClass="legend titlemantest"></asp:Label>
    </div>
    <div>
    <asp:Label ID="LabelTestCaseTitle" runat="server"  CssClass="legend titlemantest"></asp:Label>
    </div>
    <br/>
    <asp:Label ID="LabelRelatedSteps" runat="server" Text="Related Steps" CssClass="labelmantest"></asp:Label>
    <%--<asp:Image ID="ImageToStep" runat="server"  ImageUrl="~/Data/KaterinaBachvarova.jpg"/>--%>
    <asp:GridView ID="GridViewSteps" runat="server"
                     ItemType="ManTestAppWebForms.Models.Step"
                     DataKeyNames="Id"
                     DeleteMethod="GridViewSteps_DeleteItem"
                     UpdateMethod="GridViewSteps_UpdateItem"
                     SelectMethod="GridViewSteps_GetData"
                     AutoGenerateColumns="false"
                     AutoGenerateDeleteButton="false"
                     AutoGenerateEditButton="false"
                     AutoGenerateSelectButton="false"
                     
                     CssClass="table tablegridview">
         <EmptyDataTemplate>
            No data found
        </EmptyDataTemplate>
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="true"></asp:BoundField>
            <asp:BoundField DataField="Title" HeaderText="TITLE"></asp:BoundField>
            <asp:BoundField DataField="Description" HeaderText="DESCRIPTION"></asp:BoundField>
            <asp:hyperlinkfield 
                            datanavigateurlfields="Id" 
                            datanavigateurlformatstring="StepDetails.aspx?stepId={0}"
                            Text="Details >"/>
            <asp:CommandField ShowSelectButton="true" SelectText="View"/>
            <asp:CommandField ShowEditButton="True"/>
            <asp:CommandField ShowDeleteButton="True"/>
        </Columns>

    </asp:GridView>
</asp:Content>

