<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="TestCaseIndex.aspx.cs" Inherits="ManTestAppWebForms.Views.TestCaseIndex" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h2>Test Cases</h2>
    <asp:HyperLink NavigateUrl="~/Views/TestCaseCreate" Text="Add New TestCase" runat="server" />
    <asp:GridView ID="gvTestCases" runat="server"
                  AutoGenerateColumns="false"
                  ItemType="ManTestAppWebForms.Models.TestCase"
                  DataKeyNames="Id"
                  CssClass="table tablegridview"
                  SelectMethod="gvTestCases_GetData"
                  DeleteMethod="gvTestCases_DeleteItem"
                  UpdateMethod="gvTestCases_UpdateItem"
                  AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" AutoGenerateSelectButton="false"
                  AllowSorting="true" AllowPaging="true" PageSize="5"
                  EditRowStyle-CssClass="SelectedRowStyle">
        <Columns>
          <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="true"></asp:BoundField>
          <asp:BoundField DataField="Title" HeaderText="TITLE"></asp:BoundField>
          <asp:BoundField DataField="Description" HeaderText="DESCRIPTION"></asp:BoundField>
          <asp:BoundField DataField="ProjectId" HeaderText="Related Project Id"></asp:BoundField>
          <asp:BoundField DataField="ModuleId" HeaderText="Related Module Id" ></asp:BoundField>
          <asp:hyperlinkfield 
                                DataNavigateUrlFields="Id"
                                DataNavigateUrlFormatString="StepCreate.aspx?testCaseId={0}"
                                Text="Add Step"/>
            <asp:hyperlinkfield 
                                DataNavigateUrlFields="Id"
                                DataNavigateUrlFormatString="TestCaseDetails.aspx?testCaseId={0}"
                                Text="Details"/>
          <asp:CommandField ShowEditButton="True"/>
          <asp:CommandField ShowDeleteButton="True"/>
          
          <%--<asp:TemplateField>
              <ItemTemplate>
                  <asp:HyperLink ID="EditHyperLink" runat="server"  Text="Edit" NavigateUrl="~/Views/ProjectIndex.aspx"></asp:HyperLink>
                  <asp:Literal ID="Literal1" runat="server"> / </asp:Literal>
                  <asp:HyperLink ID="DeleteHyperLink" runat="server" Text="Delete" NavigateUrl="~/Views/ProjectIndex.aspx"></asp:HyperLink>
                  <asp:Literal ID="Literal2" runat="server"> / </asp:Literal>
                  <asp:HyperLink ID="DetailsHyperLink" runat="server" Text="Details" NavigateUrl="~/Views/ProjectIndex.aspx"></asp:HyperLink>
               </ItemTemplate>
              <EditItemTemplate>
                  <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
                  </EditItemTemplate>
          </asp:TemplateField>--%>
        </Columns>
    </asp:GridView>
</asp:Content>
